# Site settings
title: GEEKREPUBLIC
description: GEEKREPUBLIC
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: GEEKREPUBLIC
user_description: 
user_title: AI
email: geekrepublic@163.com
#twitter_username: lorem_ipsum
github_username:  geek-republic
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
